### ISSUE TITLE
Improve reported locations

### ISSUE THREAD

**Issue by felher** [zio/zio-profiling#6] opened 2021-11-13 22:17 UTC
Hey folks.

I created a small toy example to test the new causal profiler - and it is great! :pray: 

I used Scala 3.1. This is the toy example:

```scala
import zio._
import zio.profiling._

object Main extends ZIOAppDefault:
  def run =
    CausalProfiler
      .profile(ProfilerConfig.Default.copy(iterations = 100)) { prog.forever }
      .flatMap(_.writeToFile("profile.coz"))
      .exitCode

  val prog = for {
    done <- Ref.make(false)
    f    <- (doUselessBackgroundWork *> done.get).repeatUntilEquals(true).fork
    _    <- doRealWork
    _    <- done.set(true)
    _    <- f.join
    _    <- CausalProfiler.progressPoint("workDone")
  } yield ()

  def doRealWork = ZIO.blocking(ZIO.succeed({ Thread.sleep(100); }))

  def doUselessBackgroundWork = ZIO.blocking(ZIO.succeed({ Thread.sleep(30); }))
```

It works great and identifies correctly what should be optimized (not `doUselessBackgroundWork` but `doRealWork`, even though the second always runs longer than the first).

But when you upload the profile ([profile.txt](https://github.com/zio/zio-profiling/files/7532839/profile.txt))(needed to be .txt for github - normally it is .coz)
to https://plasma-umass.org/coz/ you notice that since there are two expressions in the definition of `doRealWork` as well as `doUselessBackgorundWork` which require an implicit `ZTraceElement`, you get two very similar locations in the profile. Like `Main.scala:20:67)` vs `Main.scala:20:68)` and `Main.scala:22:79)` vs `Main.scala:22:80)`

I have no idea how but I wondered if that could be improved. Maybe by including the expression in the location or giving a range instead of only the end column, so one can easily see which is the outer and which is the inner expression.

**Comment by mschuwalow** [comment] 2022-07-05 22:58
Hi, sorry for not working on this for so long.

The problem is that in zio 1.0 the traces included a lot of low-level operators which made good profiling output very difficult to achieve.

On the zio-2.0 branch (which will lead up to the 1.0 release of the library) profiling output will be improved in 2 ways:
1. ZIO 2.0 by default provides much better traces and that should already clean things up
2. We will support manual and automated tagging of code to be considered for profiling. The above code might look like this in the new version:

```
import zio._
import zio.profiling.causal._

object Main extends ZIOAppDefault:
  def run =
    CausalProfiler
      .profile(ProfilerConfig.Default.copy(iterations = 100)) { prog.forever }
      .flatMap(_.writeToFile("profile.coz"))
      .exitCode

  val prog = for {
    done <- Ref.make(false)
    f    <- (doUselessBackgroundWork *> done.get).repeatUntilEquals(true).fork <# "backgroundwork"
    _    <- doRealWork <# "realwork"
    _    <- done.set(true)
    _    <- f.join
    _    <- progressPoint("workDone")
  } yield ()

  def doRealWork = ZIO.blocking(ZIO.succeed({ Thread.sleep(100); }))

  def doUselessBackgroundWork = ZIO.blocking(ZIO.succeed({ Thread.sleep(30); }))
```
profiling output: [profile-new.txt](https://github.com/zio/zio-profiling/files/9050126/profile-new.txt)

Where `<#` tells the library to treat the entire effect as one 'entitiy' (thing of the callstack in normal profilers -- this works similarly, tags nest into each other and the full location of a trace includes all tags it is nested in).

When profiling you can then select exactly what you want to consider for optimization.
In this case you might use the selector `Root / *` (the default), which instructs the library to consider everything one level below root. In the above code this would mean that `backgroundwork` and `realwork` would now show up as candidates in the profiler, but lines nested in them would not (as they are included in `backgroundwork` and `realwork`).

The plan is to also support automatically extracting these Tags/Scopes from zio-telemetry spans, so you would get them for free if you put in the effort and instrumented your code using zio-telemetry.

**Comment by mschuwalow** [comment] 2023-01-27 12:46
Closing as better locations are reported starting from v0.1.0

**Closed by mschuwalow** 2023-01-27 12:46 UTC
